# Generated by Django 3.1 on 2020-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pubdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='pubdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
